//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Develop-time compiled Application Setting references
/// Generated on 2/21/2022 12:36:59 PM
/// </summary>
namespace Cinecast.Generated {
   using Cinecast.Api.Settings;
   
   
   public sealed class AppSettings_Basic {
      
      /// <summary>
      /// Accessor for the Basic AppSetting
      /// </summary>
      public static IAppSettingRef AppSetting = new AppSettingRef(@"basic");
      
      /// <summary>
      /// Definition of each PoiType in the setting
      /// </summary>
      public sealed class PoiTypes {
         
         public sealed class Hunter {
            
            /// <summary>
            /// Accessor for the Hunter PoiType
            /// </summary>
            public static IPoiTypeRef PoiType = new PoiTypeRef(@"hunter");
            
            /// <summary>
            /// Definition of each Camera in the PoiType
            /// </summary>
            public sealed class Cameras {
               
               public static IPoiTypeCameraRef World = new PoiTypeCameraRef(@"world");
               
               public static IPoiTypeCameraRef Follow = new PoiTypeCameraRef(@"follow");
            }
         }
         
         public sealed class Player {
            
            /// <summary>
            /// Accessor for the Player PoiType
            /// </summary>
            public static IPoiTypeRef PoiType = new PoiTypeRef(@"player");
            
            /// <summary>
            /// Definition of each Camera in the PoiType
            /// </summary>
            public sealed class Cameras {
               
               public static IPoiTypeCameraRef Follow = new PoiTypeCameraRef(@"follow");
               
               public static IPoiTypeCameraRef World = new PoiTypeCameraRef(@"world");
            }
         }
      }
      
      /// <summary>
      /// Definition of each interest event in the setting
      /// </summary>
      public sealed class InterestEvents {
         
         public static IPoiEventRef Attack = new PoiEventRef(@"attack");
         
         public static IPoiEventRef Hunt = new PoiEventRef(@"hunt");
         
         public static IPoiEventRef Flee = new PoiEventRef(@"flee");
      }
      
      /// <summary>
      /// Definition of each spectator event in the setting
      /// </summary>
      public sealed class SpectatorEvents {
         
         public static ISpectatorEventRef MagicRake = new SpectatorEventRef(@"magicRake");
         
         public static ISpectatorEventRef Invincible = new SpectatorEventRef(@"invincible");
      }
   }
}
